Repository FlipsideCrypto/badger, pull requests merged in 2022-10, with the labels that each got.

#4 Add feedback functionality to dashboard
  api/api/settings/base.py
  api/api/urls.py
  api/feedback/__init__.py
  api/feedback/admin.py
  api/feedback/apps.py
  api/feedback/migrations/0001_initial.py
  api/feedback/migrations/0002_alter_feedback_author.py
  api/feedback/migrations/0003_alter_feedback_author.py
  api/feedback/migrations/__init__.py
  api/feedback/models.py
  api/feedback/serializers.py
  api/feedback/urls.py
  api/feedback/views.py
  docker-compose.yml
  frontend/src/components/Card/ErrorCard.js
  frontend/src/components/Dashboard/Dashboard.js
  frontend/src/components/Dashboard/Org/Badge.js
  frontend/src/components/Dashboard/Org/BadgeForm.js
  frontend/src/components/Dashboard/Org/OrgForm.js
  frontend/src/components/Dashboard/Provider/ErrorContextProvider.js
  frontend/src/components/Dashboard/Provider/UserContextProvider.js
  frontend/src/components/Dashboard/Sidebar/HelpSidebar.js
  frontend/src/hooks/useContracts.js
  frontend/src/style/Card/ErrorCard.css
  frontend/src/style/Dashboard/Sidebar/HelpSidebar.css
  frontend/src/utils/api_requests.js
Labels: enhancement, help wanted

#29 Font Formatting for Addresses
  frontend/public/index.html
  frontend/src/components/Table/HolderTable.js
  frontend/src/style/Dashboard/Form/Input.css
Labels: enhancement

#5 Enable database backfill indexer
  api/abis.py
  api/api/settings/base.py
  api/badge/migrations/0013_alter_badge_description_alter_badge_image_hash_and_more.py
  api/badge/models.py
  api/balance/__init__.py
  api/balance/admin.py
  api/balance/apps.py
  api/balance/migrations/0001_initial.py
  api/balance/migrations/0002_transaction_balance_transactions.py
  api/balance/migrations/0003_remove_balance_balance_balance_amount.py
  api/balance/migrations/__init__.py
  api/balance/models.py
  api/balance/tests.py
  api/balance/views.py
  api/indexer/__init__.py
  api/indexer/backfill/__init__.py
  api/indexer/backfill/backfill.py
  api/indexer/backfill/extractor.py
  api/indexer/backfill/loader.py
  api/indexer/backfill/transformer.py
  api/indexer/event_signatures.py
  api/job/abis.py
  api/job/admin.py
  api/job/apps.py
  api/job/jobs.py
  api/job/listeners.py
  api/job/migrations/0008_remove_contractlistener_cron_expression_and_more.py
  api/job/models.py
  api/job/serializers.py
  api/organization/migrations/0010_organization_symbol.py
  api/organization/migrations/0011_organization_last_block.py
  api/organization/models.py
  api/utils/__init__.py
  api/utils/web3.py
  api/utils/websocket_listener.py
  contracts/abis/Badger.json
  contracts/abis/BadgerOrganization.json
  contracts/abis/BadgerScout.json
  contracts/abis/BadgerVersions.json
  contracts/contracts/Badger/BadgerVersions.sol
  contracts/contracts/BadgerOrganization/BadgerOrganization.sol
  contracts/contracts/BadgerOrganization/BadgerScout.sol
  frontend/src/abis/Badger.json
  frontend/src/abis/BadgerOrganization.json
  frontend/src/components/Dashboard/Org/BadgeForm.js
Labels: enhancement, critical

#47 Fix: Backfill indexer
  api/indexer/backfill/backfill.py
  api/indexer/backfill/loader.py
  api/organization/admin.py
  api/organization/migrations/0013_alter_organization_name.py
  api/organization/models.py
Labels: bug, critical

#44 Delegate interface support
  api/wallet/serializers.py
  api/wallet/views.py
  frontend/src/components/Card/ErrorCard.js
  frontend/src/components/Dashboard/Home/Home.js
  frontend/src/components/Dashboard/Org/Badge.js
  frontend/src/components/Dashboard/Org/BadgeForm.js
  frontend/src/components/Dashboard/Provider/OrgContextProvider.js
  frontend/src/components/Dashboard/Provider/UserContextProvider.js
  frontend/src/components/Dashboard/Sidebar/HelpSidebar.js
  frontend/src/components/Dashboard/Sidebar/OrgSidebar.js
  frontend/src/components/Dashboard/Sidebar/StatusIndicators/StatusIndicators.js
  frontend/src/hooks/useContracts.js
  frontend/src/static/constants/constants.js
  frontend/src/utils/auth.js
Labels: critical

#43 Dynamic help sidebar and copy
  frontend/src/App.css
  frontend/src/components/Card/ErrorCard.js
  frontend/src/components/Dashboard/Header/Header.js
  frontend/src/components/Dashboard/Home/Home.js
  frontend/src/components/Dashboard/Sidebar/HelpCopy.js
  frontend/src/components/Dashboard/Sidebar/HelpSidebar.js
  frontend/src/components/Dashboard/Sidebar/Logout/Logout.js
  frontend/src/components/Dashboard/Sidebar/OrgSidebar.js
  frontend/src/components/Dashboard/Sidebar/StatusIndicators/StatusIndicators.js
  frontend/src/style/Dashboard/Header/Header.css
  frontend/src/style/Dashboard/Sidebar/HelpSidebar.css
  frontend/src/style/Dashboard/Sidebar/Logout/Logout.css
  frontend/src/style/Dashboard/Sidebar/OrgSidebar.css
Labels: bug

#6 Implement contextual Badger pfps, organization and badge images
  api/badge/urls.py
  api/badge/views.py
  api/indexer/backfill/loader.py
  frontend/src/components/Dashboard/Badge/Badge.js
  frontend/src/components/Dashboard/Badge/BadgeForm.js
  frontend/src/components/Dashboard/Dashboard.js
  frontend/src/components/Dashboard/Form/ActionBar.js
  frontend/src/components/Dashboard/Form/FormDrawer.js
  frontend/src/components/Dashboard/Form/Input.js
  frontend/src/components/Dashboard/Form/InputListCSV.js
  frontend/src/components/Dashboard/Form/InputListKeyValue.js
  frontend/src/components/Dashboard/Form/Select.js
  frontend/src/components/Dashboard/Org/BadgeForm.js
  frontend/src/components/Dashboard/Org/OrgForm.js
  frontend/src/components/Dashboard/Provider/OrgContextProvider.js
  frontend/src/components/Dashboard/Sidebar/OrgSidebar.js
  frontend/src/static/constants/constants.js
  frontend/src/style/Dashboard/Badge/Badge.css
  frontend/src/style/Dashboard/Badge/BadgeForm.css
  frontend/src/style/Dashboard/Form/Input.css
  frontend/src/utils/api_requests.js
  frontend/src/utils/helpers.js
Labels: enhancement

#52 Responsive clean-up for landing page and dashboard
  frontend/src/components/Button/IconButton.js
  frontend/src/components/Dashboard/Badge/Badge.js
  frontend/src/components/Dashboard/Dashboard.js
  frontend/src/components/Dashboard/Home/Home.js
  frontend/src/components/Dashboard/Mobile/MobilePreventor.js
  frontend/src/components/Dashboard/Org/Org.js
  frontend/src/components/Dashboard/Sidebar/OrgSidebar.js
  frontend/src/style/Button/IconButton.css
  frontend/src/style/Dashboard/Mobile/MobilePreventor.css
  frontend/src/style/Dashboard/Sidebar/OrgSidebar.css
  frontend/src/style/Landing.css
Labels: documentation, enhancement, critical

#112 feat: use of official domain
  api/api/settings/production.py
Labels: critical
