Repository FlipsideCrypto/badger, pull requests merged in 2022-11, with the labels that each got.

#107 Delay/Multiple Clicks of Run Transaction Buttons
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/components/Button/IconButton.js
  frontend/src/components/Dashboard/Badge/Badge.js
  frontend/src/components/Dashboard/Badge/BadgeForm.js
  frontend/src/components/Dashboard/Form/ActionBar.js
  frontend/src/components/Dashboard/Form/FormDrawer.js
  frontend/src/components/Dashboard/Form/FormReducer.js
  frontend/src/components/Dashboard/Form/Help.js
  frontend/src/components/Dashboard/Form/InputListCSV.js
  frontend/src/components/Dashboard/Form/InputListKeyValue.js
  frontend/src/components/Dashboard/Header/Header.js
  frontend/src/components/Dashboard/Home/Home.js
  frontend/src/components/Dashboard/Mobile/MobilePreventor.js
  frontend/src/components/Dashboard/Org/OrgForm.js
  frontend/src/components/Dashboard/Sidebar/OrgSidebar.js
  frontend/src/components/Landing.js
  frontend/src/hooks/useContracts.js
  frontend/src/hooks/useIpfsHash.js
  frontend/src/index.js
  frontend/src/style/Button/IconButton.css
  frontend/src/style/Dashboard/Dashboard.css
  frontend/src/style/Dashboard/Form/ActionBar.css
  frontend/src/style/Dashboard/Form/FormDrawer.css
  frontend/src/style/Dashboard/Form/Input.css
  frontend/src/utils/api_requests.js
Labels: bug, help wanted, open building

#119 118 fix replay attacks
  api/abis.py
  api/api/settings/base.py
  api/indexer/backfill/backfill.py
  api/indexer/backfill/loader.py
  api/job/apps.py
  api/job/jobs.py
  api/job/migrations/0010_remove_contractlistener_abi_contractlistener_version.py
  api/job/models.py
  api/job/serializers.py
  api/organization/migrations/0014_organization_version.py
  api/organization/models.py
  api/organization/serializers.py
  contracts/README.md
  contracts/abis/BadgerOrganization.json
  contracts/abis/BadgerOrganizationInterface.json
  contracts/abis/BadgerScout.json
  contracts/contracts/BadgerOrganization/BadgerOrganization.sol
  contracts/contracts/BadgerOrganization/BadgerScout.sol
  contracts/contracts/BadgerOrganization/interfaces/BadgerOrganizationInterface.sol
  contracts/test/Badger.js
  frontend/src/abis/4.0_Badger.json
  frontend/src/abis/4.0_BadgerOrganization.json
  frontend/src/abis/5.0_Badger.json
  frontend/src/abis/5.0_BadgerOrganization.json
  frontend/src/components/Dashboard/Badge/Badge.js
  frontend/src/components/Dashboard/Badge/BadgeForm.js
  frontend/src/components/Dashboard/Org/OrgForm.js
  frontend/src/hooks/useContracts.js
Labels: bug

#129 fix: contract update and tests
  contracts/abis/Badger.json
  contracts/abis/BadgerOrganization.json
  contracts/abis/BadgerVersions.json
  contracts/abis/BadgerVersionsInterface.json
  contracts/contracts/Badger/BadgerVersions.sol
  contracts/contracts/Badger/interfaces/BadgerVersionsInterface.sol
  contracts/contracts/BadgerOrganization/BadgerOrganization.sol
  contracts/test/Badger.js
Labels: bug, critical

#131 Checksumming Addresses
  frontend/src/components/Dashboard/Badge/Badge.js
  frontend/src/components/Dashboard/Badge/BadgeForm.js
  frontend/src/components/Dashboard/Form/InputListCSV.js
  frontend/src/utils/api_requests.js
  frontend/src/utils/helpers.js
Labels: bug, critical

#145 fix: home card performance
  frontend/src/components/Dashboard/Home/Home.js
  frontend/src/components/Dashboard/Org/Org.js
  frontend/src/style/Dashboard/Home/Home.css
Labels: bug, critical

#155 Feature: Organizational Ownership Transfer
  api/organization/views.py
  frontend/src/App.css
  frontend/src/components/Dashboard/Badge/BadgeDangerZone.js
  frontend/src/components/Dashboard/Badge/BadgeForm.js
  frontend/src/components/Dashboard/Form/InputAddress.js
  frontend/src/components/Dashboard/Org/OrgDangerZone.js
  frontend/src/style/Dashboard/Form/Input.css
  frontend/src/utils/api_requests.js
Labels: enhancement

#159 fix: blurred home organization cards
  frontend/src/components/Dashboard/Home/Home.js
  frontend/src/components/Dashboard/Utils/ImageLoader.js
  frontend/src/hooks/useColor.js
  frontend/src/style/Dashboard/Home/Home.css
Labels: bug
