Repository FlipsideCrypto/badger, pull requests merged in 2023-03, with the labels that each got.

#188 feat: better indexer that supports new contracts
  api/api/settings/base.py
  api/indexer/extractor.py
  api/indexer/listener.py
  api/indexer/loader.py
  api/indexer/management/commands/listen_for_factories.py
  api/indexer/management/commands/listen_for_organizations.py
  api/utils/web3.py
  api/utils/websocket_listener.py
  contracts/build/gas-report.txt
  contracts/hardhat.config.js
Labels: enhancement, critical

#192 feat: functional multi-object indexer
  api/api/settings/base.py
  api/badge/migrations/0016_alter_badge_is_active.py
  api/badge/models.py
  api/indexer/extractor.py
  api/indexer/listener.py
  api/indexer/loader.py
  api/organization/migrations/0015_alter_organization_is_active.py
  api/organization/models.py
  api/organization/serializers.py
  contracts/build/gas-report.txt
  docker-compose.yml
  frontend/src/hooks/contracts/useContracts.js
Labels: bug, critical

#194 feat: openapi + api url kwargs + requirements
  api/api/settings/base.py
  api/api/templates/docs.html
  api/api/urls.py
  api/badge/serializers.py
  api/badge/views.py
  api/requirements.txt
  frontend/src/utils/api.js
Labels: documentation, enhancement

#199 feat: make navbar mobile-friendly
  contracts/build/gas-report.txt
  frontend/src/components/Bar/ActionBar.js
  frontend/src/components/Button/ActionButton.js
  frontend/src/style/Bar/ActionBar.css
  frontend/src/style/Dashboard/Dashboard.css
Labels: enhancement

#200 feat: onchain organization archive
  api/abis/BadgerOrganization.json
  api/abis/BadgerOrganizationLogic.json
  api/abis/IBadgerOrganizationLogic.json
  api/abis/full/Badger.json
  api/abis/full/BadgerForfeitForbidden.json
  api/abis/full/BadgerForfeitHook.json
  api/abis/full/BadgerHook.json
  api/abis/full/BadgerHookBlocklist.json
  api/abis/full/BadgerHookHook.json
  api/abis/full/BadgerHooked.json
  api/abis/full/BadgerManaged.json
  api/abis/full/BadgerManager.json
  api/abis/full/BadgerManagerClaimable.json
  api/abis/full/BadgerManagerSignature.json
  api/abis/full/BadgerMintHook.json
  api/abis/full/BadgerMintMax.json
  api/abis/full/BadgerMintMaxAllowance.json
  api/abis/full/BadgerMintMaxSupply.json
  api/abis/full/BadgerMintSelf.json
  api/abis/full/BadgerOrganization.json
  api/abis/full/BadgerOrganizationLogic.json
  api/abis/full/BadgerRevokeForbidden.json
  api/abis/full/BadgerRevokeHook.json
  api/abis/full/BadgerTransferBlocklist.json
  api/abis/full/BadgerTransferBound.json
  api/abis/full/BadgerTransferBoundManaged.json
  api/abis/full/BadgerTransferHook.json
  api/abis/full/ContextUpgradeable.json
  api/abis/full/ERC1155Upgradeable.json
  api/abis/full/ERC165.json
  api/abis/full/ERC165Upgradeable.json
  api/abis/full/IBadger.json
  api/abis/full/IBadgerConfigured.json
  api/abis/full/IBadgerHook.json
  api/abis/full/IBadgerHooked.json
  api/abis/full/IBadgerManaged.json
  api/abis/full/IBadgerOrganization.json
  api/abis/full/IBadgerOrganizationLogic.json
  api/abis/full/IERC1155MetadataURIUpgradeable.json
  api/abis/full/IERC1155ReceiverUpgradeable.json
  api/abis/full/IERC1155Upgradeable.json
  api/abis/full/IERC165.json
  api/abis/full/IERC165Upgradeable.json
  api/abis/full/Initializable.json
  api/abis/full/Multicallable.json
  api/abis/full/OwnableUpgradeable.json
  contracts/README.md
  contracts/build/abis/BadgerOrganization.json
  contracts/build/abis/BadgerOrganizationLogic.json
  contracts/build/abis/IBadgerOrganizationLogic.json
  contracts/build/c4udit-report.md
  contracts/build/gas-report.txt
  contracts/contracts/BadgerOrganizationLogic.sol
  contracts/contracts/interfaces/IBadgerOrganizationLogic.sol
  contracts/test/Badger.js
  contracts/test/hooks/revoke/BadgerRevokeForbidden.js
  frontend/src/abis/BadgerOrganization.json
  frontend/src/abis/BadgerOrganizationLogic.json
  frontend/src/abis/IBadgerOrganizationLogic.json
Labels: critical

#201 fix: abi exports
  api/abis.py
  api/abis/Badger.json
  api/abis/BadgerForfeitForbidden.json
  api/abis/BadgerForfeitHook.json
  api/abis/BadgerHook.json
  api/abis/BadgerHookBlocklist.json
  api/abis/BadgerHookHook.json
  api/abis/BadgerHooked.json
  api/abis/BadgerManaged.json
  api/abis/BadgerManager.json
  api/abis/BadgerManagerClaimable.json
  api/abis/BadgerManagerSignature.json
  api/abis/BadgerMintHook.json
  api/abis/BadgerMintMax.json
  api/abis/BadgerMintMaxAllowance.json
  api/abis/BadgerMintMaxSupply.json
  api/abis/BadgerMintSelf.json
  api/abis/BadgerOrganization.json
  api/abis/BadgerOrganizationLogic.json
  api/abis/BadgerRevokeForbidden.json
  api/abis/BadgerRevokeHook.json
  api/abis/BadgerTransferBlocklist.json
  api/abis/BadgerTransferBound.json
  api/abis/BadgerTransferBoundManaged.json
  api/abis/BadgerTransferHook.json
  api/abis/ContextUpgradeable.json
  api/abis/ERC1155Upgradeable.json
  api/abis/ERC165.json
  api/abis/ERC165Upgradeable.json
  api/abis/IBadger.json
  api/abis/IBadgerConfigured.json
  api/abis/IBadgerHook.json
  api/abis/IBadgerHooked.json
  api/abis/IBadgerManaged.json
  api/abis/IBadgerOrganization.json
  api/abis/IBadgerOrganizationLogic.json
  api/abis/IERC1155MetadataURIUpgradeable.json
  api/abis/IERC1155ReceiverUpgradeable.json
  api/abis/IERC1155Upgradeable.json
  api/abis/IERC165.json
  api/abis/IERC165Upgradeable.json
  api/abis/Initializable.json
  api/abis/Multicallable.json
  api/abis/OwnableUpgradeable.json
  api/api/settings/base.py
  api/indexer/listener.py
  api/indexer/loader.py
  contracts/hardhat.config.js
Labels: bug

#202 feat: new design implemented for buttons
  frontend/src/components/Bar/ActionBar.js
  frontend/src/components/Bar/FormActionBar.js
  frontend/src/components/Button/ActionButton.js
  frontend/src/components/Button/IconButton.js
  frontend/src/components/Button/LogoutButton.js
  frontend/src/components/Button/index.js
  frontend/src/components/Drawer/BadgeManagementDrawer.js
  frontend/src/components/Empty/Empty.js
  frontend/src/components/Header/Header.js
  frontend/src/components/View/OrgView.js
  frontend/src/components/index.js
  frontend/src/pages/Home/Home.js
  frontend/src/pages/Org/Org.js
  frontend/src/pages/Org/OrgForm.js
  frontend/src/style/App.css
  frontend/src/style/Button/ActionButton.css
  frontend/src/style/Empty/Empty.css
Labels: enhancement

#203 feat: data source as websockets → logs → listener → backfill
  contracts/build/gas-report.txt
  frontend/src/components/Bar/ActionBar.js
  frontend/src/components/Dashboard/DashboardLoader.js
  frontend/src/components/Dashboard/index.js
  frontend/src/components/View/OrgView.js
  frontend/src/components/View/ProfileView.js
  frontend/src/components/index.js
  frontend/src/hooks/contracts/useContracts.js
  frontend/src/pages/Org/Org.js
  frontend/src/style/App.css
  frontend/src/style/Bar/ActionBar.css
  frontend/src/style/Dashboard/Dashboard.css
  frontend/src/style/Empty/Empty.css
  frontend/src/style/Header/Header.css
  frontend/src/style/View/OrgView.css
  frontend/src/style/pages/Home.css
Labels: enhancement

#206 feat: complete websocket usage
  api/badge/serializers.py
  api/balance/migrations/0002_alter_transaction_unique_together.py
  api/balance/models.py
  contracts/build/gas-report.txt
  frontend/src/hooks/useUser.js
Labels: bug, enhancement, critical

#207 feat: goodbye authentication
  api/api/mixins.py
  api/api/permissions.py
  api/api/settings/base.py
  api/api/urls.py
  api/api/views.py
  api/badge/consumers.py
  api/badge/views.py
  api/ipfs/views.py
  api/organization/consumers.py
  api/organization/views.py
  api/wallet/views.py
  contracts/build/gas-report.txt
  frontend/src/components/Bar/ActionBar.js
  frontend/src/components/Button/ConnectButton.js
  frontend/src/contexts/AuthenticationContext.js
  frontend/src/hooks/contracts/useBadgeForm.js
  frontend/src/hooks/contracts/useContracts.js
  frontend/src/hooks/contracts/useManageHolders.js
  frontend/src/hooks/contracts/useSetManagers.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useAuthentication.js
  frontend/src/hooks/useAuthenticationModal.js
  frontend/src/hooks/useLogout.js
  frontend/src/hooks/useUser.js
  frontend/src/pages/Badge/Badge.js
  frontend/src/pages/Dashboard/Dashboard.js
  frontend/src/pages/Home/Home.js
  frontend/src/pages/Org/OrgForm.js
  frontend/src/utils/auth.js
  frontend/src/utils/index.js
Labels: enhancement, critical, game changing

#208 fix: generated images and color cards
  api/badge/views.py
  contracts/build/gas-report.txt
  frontend/src/components/Button/ConnectButton.js
  frontend/src/components/Utils/ImageLoader.js
  frontend/src/components/View/OrgView.js
  frontend/src/components/View/ProfileView.js
  frontend/src/hooks/useColor.js
  frontend/src/hooks/useENSProfile.js
  frontend/src/style/Bar/ActionBar.css
  frontend/src/style/Card/OrgCard.css
  frontend/src/style/View/OrgView.css
Labels: bug

#210 fix: spaces in badge name
  api/badge/views.py
  api/indexer/loader.py
  contracts/build/gas-report.txt
  frontend/public/safari-pinned-tab.svg
  frontend/src/components/Card/OrgCard.js
  frontend/src/components/Table/BadgeTable.js
  frontend/src/components/Utils/ImageLoader.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useBadgeArt.js
  frontend/src/hooks/useColor.js
  frontend/src/hooks/useDebounce.js
  frontend/src/hooks/usePFP.js
  frontend/src/pages/Badge/BadgeForm.js
  frontend/src/pages/Media/Media.js
  frontend/src/pages/Org/OrgForm.js
  frontend/src/style/Accordion/Accordion.css
  frontend/src/style/App.css
  frontend/src/style/Bar/ActionBar.css
  frontend/src/style/Bar/FormActionBar.css
  frontend/src/style/Button/ActionButton.css
  frontend/src/style/Button/Button.css
  frontend/src/style/Button/IconButton.css
  frontend/src/style/Card/OrgCard.css
  frontend/src/style/Card/StoryCard.css
  frontend/src/style/Dashboard/Dashboard.css
  frontend/src/style/Empty/Empty.css
  frontend/src/style/Form/Checkbox.css
  frontend/src/style/Form/FormDrawer.css
  frontend/src/style/Form/Select.css
  frontend/src/style/Form/Switch.css
  frontend/src/style/Hero/LandingHero.css
  frontend/src/style/Link/ArrowLink.css
  frontend/src/style/Navbar/Navbar.css
  frontend/src/style/Sidebar/HelpSidebar.css
  frontend/src/style/Sidebar/OrgSidebar.css
  frontend/src/style/Table/HolderTable.css
  frontend/src/style/View/OrgView.css
  frontend/src/style/index.css
  frontend/src/style/pages/Badge.css
  frontend/src/style/pages/BadgeForm.css
  frontend/src/style/pages/Home.css
  frontend/src/style/pages/Landing.css
  frontend/src/style/pages/Media.css
  frontend/src/style/pages/Story.css
Labels: bug, critical

#212 fix: save() ens fields
  api/wallet/signals.py
  contracts/build/gas-report.txt
Labels: enhancement

#211 fix: holder table multicall mint and revoking
  frontend/src/components/Table/HolderTable.js
  frontend/src/hooks/contracts/useBadgeForm.js
  frontend/src/hooks/contracts/useManageHolders.js
  frontend/src/pages/Badge/BadgeForm.js
  frontend/src/style/Table/HolderTable.css
  frontend/src/utils/validation.js
Labels: critical

#220 feat: better user architecture
  api/badge/serializers.py
  api/indexer/loader.py
  contracts/build/gas-report.txt
  frontend/src/components/Dashboard/Dashboard.js
  frontend/src/components/Dashboard/DashboardLoader.js
  frontend/src/components/Wallet/Wallet.js
  frontend/src/contexts/UserContext.js
  frontend/src/hooks/useBadgeArt.js
  frontend/src/hooks/useUser.js
  frontend/src/pages/Badge/Badge.js
  frontend/src/pages/Badge/BadgeForm.js
  frontend/src/pages/Dashboard/Dashboard.js
  frontend/src/pages/Org/Org.js
  frontend/src/pages/Org/OrgForm.js
  frontend/src/style/Empty/Empty.css
Labels: critical

#226 feat: organization discovery w/ user exploration
  .github/workflows/hardhat.js.yml
  api/api/routing.py
  api/badge/consumers.py
  api/indexer/listener.py
  api/indexer/loader.py
  api/organization/consumers.py
  api/organization/models.py
  api/organization/views.py
  contracts/build/gas-report.txt
  frontend/src/App.js
  frontend/src/components/Bar/ActionBar.js
  frontend/src/components/Card/OrgCard.js
  frontend/src/components/DangerZone/BadgeDangerZone.js
  frontend/src/components/Dashboard/Dashboard.js
  frontend/src/components/Dashboard/DashboardLoader.js
  frontend/src/components/Dashboard/DashboardWrapper.js
  frontend/src/components/Dashboard/index.js
  frontend/src/components/Form/Input/InputAmountDelete.js
  frontend/src/components/Table/BadgeTable.js
  frontend/src/components/Table/HolderTable.js
  frontend/src/components/Table/ManagerTable.js
  frontend/src/components/Table/OrgTable.js
  frontend/src/components/View/OrgView.js
  frontend/src/components/index.js
  frontend/src/contexts/AddressContext.js
  frontend/src/contexts/AuthenticationContext.js
  frontend/src/contexts/BadgeContext.js
  frontend/src/contexts/OrgContext.js
  frontend/src/contexts/UserContext.js
  frontend/src/contexts/index.js
  frontend/src/hooks/contracts/useOrgForm.js
  frontend/src/hooks/contracts/useTransferOwnership.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useLogout.js
  frontend/src/hooks/useNavigateAddress.js
  frontend/src/hooks/usePFP.js
  frontend/src/hooks/useSocket.js
  frontend/src/hooks/useTabActive.js
  frontend/src/hooks/useUser.js
  frontend/src/pages/Badge/Badge.js
  frontend/src/pages/Badge/BadgeForm.js
  frontend/src/pages/Dashboard/Dashboard.js
  frontend/src/pages/Discover/Discover.js
  frontend/src/pages/Home/Home.js
  frontend/src/pages/Org/Org.js
  frontend/src/pages/Org/OrgForm.js
Labels: bug, enhancement, game changing

#231 fix: changing connected wallets
  frontend/src/components/Dashboard/DashboardLoader.js
  frontend/src/hooks/useSocket.js
Labels: bug, critical

#236 feat: no more onchain archived
  api/abis/BadgerOrganization.json
  api/abis/BadgerOrganizationLogic.json
  api/abis/IBadgerOrganizationLogic.json
  api/abis/full/BadgerOrganization.json
  api/abis/full/BadgerOrganizationLogic.json
  api/abis/full/IBadgerOrganizationLogic.json
  contracts/build/abis/BadgerOrganization.json
  contracts/build/abis/BadgerOrganizationLogic.json
  contracts/build/abis/IBadgerOrganizationLogic.json
  contracts/build/gas-report.txt
  contracts/contracts/BadgerOrganizationLogic.sol
  contracts/contracts/interfaces/IBadgerOrganizationLogic.sol
  contracts/test/Badger.js
  frontend/src/abis/BadgerOrganization.json
  frontend/src/abis/BadgerOrganizationLogic.json
  frontend/src/abis/IBadgerOrganizationLogic.json
Labels: enhancement

#235 feat: badge archiving
  api/abis/Badger.json
  api/abis/BadgerOrganization.json
  api/abis/BadgerOrganizationLogic.json
  api/abis/IBadger.json
  api/abis/IBadgerOrganizationLogic.json
  api/abis/full/Badger.json
  api/abis/full/BadgerOrganization.json
  api/abis/full/BadgerOrganizationLogic.json
  api/abis/full/IBadger.json
  api/abis/full/IBadgerOrganizationLogic.json
  api/indexer/loader.py
  api/organization/models.py
  contracts/build/abis/Badger.json
  contracts/build/abis/BadgerOrganization.json
  contracts/build/abis/BadgerOrganizationLogic.json
  contracts/build/abis/IBadger.json
  contracts/build/abis/IBadgerOrganizationLogic.json
  contracts/build/gas-report.txt
  contracts/contracts/Badger.sol
  contracts/contracts/BadgerOrganizationLogic.sol
  contracts/contracts/interfaces/IBadgerOrganizationLogic.sol
  contracts/contracts/interfaces/IBadgerOrganizationStruct.sol
  contracts/test/Badger.js
  frontend/src/abis/Badger.json
  frontend/src/abis/BadgerOrganization.json
  frontend/src/abis/BadgerOrganizationLogic.json
  frontend/src/abis/IBadger.json
  frontend/src/abis/IBadgerOrganizationLogic.json
  frontend/src/components/Form/FormReducer.js
  frontend/src/hooks/contracts/useOrgForm.js
  frontend/src/pages/Org/OrgForm.js
Labels: enhancement

#237 feat: uri as a database
  api/abis/Badger.json
  api/abis/BadgerOrganization.json
  api/abis/BadgerOrganizationLogic.json
  api/abis/IBadger.json
  api/abis/IBadgerOrganizationLogic.json
  api/abis/full/Badger.json
  api/abis/full/BadgerOrganization.json
  api/abis/full/BadgerOrganizationLogic.json
  api/abis/full/IBadger.json
  api/abis/full/IBadgerOrganizationLogic.json
  api/indexer/loader.py
  api/organization/models.py
  contracts/build/abis/Badger.json
  contracts/build/abis/BadgerOrganization.json
  contracts/build/abis/BadgerOrganizationLogic.json
  contracts/build/abis/IBadger.json
  contracts/build/abis/IBadgerOrganizationLogic.json
  contracts/build/gas-report.txt
  contracts/contracts/Badger.sol
  contracts/contracts/BadgerOrganizationLogic.sol
  contracts/contracts/interfaces/IBadgerOrganizationLogic.sol
  contracts/contracts/interfaces/IBadgerOrganizationStruct.sol
  contracts/test/Badger.js
  frontend/src/App.js
  frontend/src/abis/Badger.json
  frontend/src/abis/BadgerOrganization.json
  frontend/src/abis/BadgerOrganizationLogic.json
  frontend/src/abis/IBadger.json
  frontend/src/abis/IBadgerOrganizationLogic.json
  frontend/src/components/Form/FormReducer.js
  frontend/src/hooks/contracts/useOrgForm.js
  frontend/src/pages/Landing/Landing.js
  frontend/src/pages/Org/OrgForm.js
  frontend/src/pages/Page/Hero.js
  frontend/src/pages/Page/index.js
  frontend/src/pages/index.js
Labels: enhancement

#245 fix: self retrieved organizations
  api/organization/models.py
  api/organization/views.py
  frontend/src/hooks/useSocket.js
Labels: bug, critical

#246 fix: editing images
  frontend/src/pages/Badge/BadgeForm.js
  frontend/src/pages/Org/OrgForm.js
Labels: bug, critical
